/**
 * types.ts
 * 
 * TypeScript type definitions for the Roman Empire Encyclopedia content schema.
 * This file defines the structured data shapes for topics, sections, timelines,
 * and other historical content generated by Gemini or hand-authored.
 */

/**
 * Union type representing the 6 main content sections of the encyclopedia.
 */
export type SectionSlug =
  | "zaman-cizelgesi"
  | "din-mitoloji"
  | "kultur-toplum"
  | "ekonomi"
  | "siyaset-hukuk"
  | "askeri";

/**
 * Represents an entry in the master topic list (data/topicList.json).
 * This is the metadata index used to drive content generation and navigation.
 */
export interface TopicListEntry {
  slug: string;
  section: SectionSlug;
  title_tr: string;
  category: string;
  short_desc: string;
  era_tag: string | null;
}

/**
 * Represents a chronological event, used in timelines across various topics.
 */
export interface TimelineEvent {
  year: string;         // e.g., "M.Ö. 753", "M.S. 476", "1914-1918"
  title: string;        // Short Turkish title of the event
  description: string;  // Detailed explanation (2-3 sentences)
  era?: string;         // Optional broad era label (e.g., "Cumhuriyet", "Geç İmparatorluk")
}

/**
 * Represents a notable historical figure associated with a specific topic.
 */
export interface KeyFigure {
  name: string;         // e.g., "Julius Caesar", "Augustus"
  role: string;         // e.g., "Diktatör, General", "İlk İmparator"
  lifespan?: string;    // e.g., "M.Ö. 100 - M.Ö. 44"
  description: string;  // Brief summary of their significance to this topic
}

/**
 * Represents a note on historical uncertainty, scholarly debate, or disputed facts.
 * This is a key differentiator to ensure academic-grade depth over simple summaries.
 */
export interface SourceNote {
  note: string;         // Explanation of the debate (e.g., "Romulus'un tarihsel varlığı modern tarihçilerce tartışmalıdır...")
}

/**
 * Represents a Latin or technical term introduced in the topic, with its definition.
 */
export interface KeyTerm {
  term: string;         // e.g., "Cursus Honorum", "Pater Familias"
  definition: string;  // Turkish explanation of the term
}

/**
 * The main rich content payload generated by Gemini for each individual topic.
 * Designed to be deeply comprehensive, structured, and highly readable.
 */
export interface TopicContent {
  overview: string;                    // 3-5 sentence academic/encyclopedic introduction
  body: {
    heading: string;                   // Subsection title (e.g., "Marius Reformları'nın Etkileri")
    paragraphs: string[];              // 2-4 paragraphs of detailed prose per subsection
  }[];                                 // 3-6 body subsections covering the topic in depth
  timeline?: TimelineEvent[];          // Optional chronological events relevant to this specific topic
  keyFigures?: KeyFigure[];            // Optional notable people associated with this topic
  keyTerms?: KeyTerm[];                // Optional glossary of Latin/technical terms introduced
  didYouKnow?: string[];               // Optional array of 2-4 short "interesting fact" callouts
  disputedPoints?: SourceNote[];       // Optional array flagging genuine historical uncertainty/scholarly debate
  relatedTopicSlugs?: string[];        // Optional cross-links to other topic slugs for site-wide navigation
}

/**
 * Represents the complete structure of a generated topic JSON file.
 * Saved under data/topics/<slug>.json.
 */
export interface GeneratedTopicFile {
  slug: string;
  section: SectionSlug;
  title_tr: string;
  generatedAt: string;                 // ISO timestamp of generation
  content: TopicContent;
}

/**
 * Represents an era-level summary card for the zaman-cizelgesi (timeline) section.
 * Used to group individual topics into broad chronological chapters.
 */
export interface EraSummary {
  eraSlug: string;                     // e.g., "roma-kralligi", "roma-cumhuriyeti"
  eraName_tr: string;                  // e.g., "Roma Krallığı Dönemi"
  approxYears: string;                 // e.g., "M.Ö. 753 - M.Ö. 509"
  shortSummary: string;                // 2-3 sentence overview of the era's significance
  colorAccent?: string;                // Optional Tailwind color class override
}